// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package io.github.ccxt.api;
import io.github.ccxt.Exchange;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

public class IndodaxApi extends Exchange
{

    public IndodaxApi () {
        super();
    }

    public IndodaxApi (Object options) {
        super(options);
    }

    /**
     * Calls the publicGetApiServerTime endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  publicGetApiServerTime (Object... optionalArgs)
    {
        return this.callAsync ("publicGetApiServerTime", optionalArgs);
    }

    /**
     * Calls the publicGetApiPairs endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON array
     */
    public CompletableFuture<List<Object>>  publicGetApiPairs (Object... optionalArgs)
    {
        return this.callAsync ("publicGetApiPairs", optionalArgs);
    }

    /**
     * Calls the publicGetApiPriceIncrements endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  publicGetApiPriceIncrements (Object... optionalArgs)
    {
        return this.callAsync ("publicGetApiPriceIncrements", optionalArgs);
    }

    /**
     * Calls the publicGetApiSummaries endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  publicGetApiSummaries (Object... optionalArgs)
    {
        return this.callAsync ("publicGetApiSummaries", optionalArgs);
    }

    /**
     * Calls the publicGetApiTickerPair endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  publicGetApiTickerPair (Object... optionalArgs)
    {
        return this.callAsync ("publicGetApiTickerPair", optionalArgs);
    }

    /**
     * Calls the publicGetApiTickerAll endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  publicGetApiTickerAll (Object... optionalArgs)
    {
        return this.callAsync ("publicGetApiTickerAll", optionalArgs);
    }

    /**
     * Calls the publicGetApiTradesPair endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON array
     */
    public CompletableFuture<List<Object>>  publicGetApiTradesPair (Object... optionalArgs)
    {
        return this.callAsync ("publicGetApiTradesPair", optionalArgs);
    }

    /**
     * Calls the publicGetApiDepthPair endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  publicGetApiDepthPair (Object... optionalArgs)
    {
        return this.callAsync ("publicGetApiDepthPair", optionalArgs);
    }

    /**
     * Calls the publicGetTradingviewHistoryV2 endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON array
     */
    public CompletableFuture<List<Object>>  publicGetTradingviewHistoryV2 (Object... optionalArgs)
    {
        return this.callAsync ("publicGetTradingviewHistoryV2", optionalArgs);
    }

    /**
     * Calls the privatePostGetInfo endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  privatePostGetInfo (Object... optionalArgs)
    {
        return this.callAsync ("privatePostGetInfo", optionalArgs);
    }

    /**
     * Calls the privatePostTransHistory endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  privatePostTransHistory (Object... optionalArgs)
    {
        return this.callAsync ("privatePostTransHistory", optionalArgs);
    }

    /**
     * Calls the privatePostTrade endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  privatePostTrade (Object... optionalArgs)
    {
        return this.callAsync ("privatePostTrade", optionalArgs);
    }

    /**
     * Calls the privatePostTradeHistory endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  privatePostTradeHistory (Object... optionalArgs)
    {
        return this.callAsync ("privatePostTradeHistory", optionalArgs);
    }

    /**
     * Calls the privatePostOpenOrders endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  privatePostOpenOrders (Object... optionalArgs)
    {
        return this.callAsync ("privatePostOpenOrders", optionalArgs);
    }

    /**
     * Calls the privatePostOrderHistory endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  privatePostOrderHistory (Object... optionalArgs)
    {
        return this.callAsync ("privatePostOrderHistory", optionalArgs);
    }

    /**
     * Calls the privatePostGetOrder endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  privatePostGetOrder (Object... optionalArgs)
    {
        return this.callAsync ("privatePostGetOrder", optionalArgs);
    }

    /**
     * Calls the privatePostGetOrderByClientOrderId endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  privatePostGetOrderByClientOrderId (Object... optionalArgs)
    {
        return this.callAsync ("privatePostGetOrderByClientOrderId", optionalArgs);
    }

    /**
     * Calls the privatePostCancelOrder endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  privatePostCancelOrder (Object... optionalArgs)
    {
        return this.callAsync ("privatePostCancelOrder", optionalArgs);
    }

    /**
     * Calls the privatePostCancelByClientOrderId endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  privatePostCancelByClientOrderId (Object... optionalArgs)
    {
        return this.callAsync ("privatePostCancelByClientOrderId", optionalArgs);
    }

    /**
     * Calls the privatePostWithdrawFee endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  privatePostWithdrawFee (Object... optionalArgs)
    {
        return this.callAsync ("privatePostWithdrawFee", optionalArgs);
    }

    /**
     * Calls the privatePostWithdrawCoin endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  privatePostWithdrawCoin (Object... optionalArgs)
    {
        return this.callAsync ("privatePostWithdrawCoin", optionalArgs);
    }

    /**
     * Calls the privatePostListDownline endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  privatePostListDownline (Object... optionalArgs)
    {
        return this.callAsync ("privatePostListDownline", optionalArgs);
    }

    /**
     * Calls the privatePostCheckDownline endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  privatePostCheckDownline (Object... optionalArgs)
    {
        return this.callAsync ("privatePostCheckDownline", optionalArgs);
    }

    /**
     * Calls the privatePostCreateVoucher endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  privatePostCreateVoucher (Object... optionalArgs)
    {
        return this.callAsync ("privatePostCreateVoucher", optionalArgs);
    }

    /**
     * Calls the deadmanPostCountdownCancelAll endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  deadmanPostCountdownCancelAll (Object... optionalArgs)
    {
        return this.callAsync ("deadmanPostCountdownCancelAll", optionalArgs);
    }

    /**
     * Calls the v2GetOrder endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  v2GetOrder (Object... optionalArgs)
    {
        return this.callAsync ("v2GetOrder", optionalArgs);
    }

    /**
     * Calls the v2GetOpenOrders endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON array
     */
    public CompletableFuture<List<Object>>  v2GetOpenOrders (Object... optionalArgs)
    {
        return this.callAsync ("v2GetOpenOrders", optionalArgs);
    }

    /**
     * Calls the v2GetOrderHistories endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  v2GetOrderHistories (Object... optionalArgs)
    {
        return this.callAsync ("v2GetOrderHistories", optionalArgs);
    }

    /**
     * Calls the v2GetMyTrades endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  v2GetMyTrades (Object... optionalArgs)
    {
        return this.callAsync ("v2GetMyTrades", optionalArgs);
    }

    /**
     * Calls the v2GetAccount endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  v2GetAccount (Object... optionalArgs)
    {
        return this.callAsync ("v2GetAccount", optionalArgs);
    }

    /**
     * Calls the v2GetCapitalWithdrawHistory endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON array
     */
    public CompletableFuture<List<Object>>  v2GetCapitalWithdrawHistory (Object... optionalArgs)
    {
        return this.callAsync ("v2GetCapitalWithdrawHistory", optionalArgs);
    }

    /**
     * Calls the v2GetCapitalDepositHisrec endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON array
     */
    public CompletableFuture<List<Object>>  v2GetCapitalDepositHisrec (Object... optionalArgs)
    {
        return this.callAsync ("v2GetCapitalDepositHisrec", optionalArgs);
    }

    /**
     * Calls the v2GetCapitalDepositAddressList endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON array
     */
    public CompletableFuture<List<Object>>  v2GetCapitalDepositAddressList (Object... optionalArgs)
    {
        return this.callAsync ("v2GetCapitalDepositAddressList", optionalArgs);
    }

    /**
     * Calls the v2GetFiatOrders endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  v2GetFiatOrders (Object... optionalArgs)
    {
        return this.callAsync ("v2GetFiatOrders", optionalArgs);
    }

    /**
     * Calls the v2PostOrder endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  v2PostOrder (Object... optionalArgs)
    {
        return this.callAsync ("v2PostOrder", optionalArgs);
    }

    /**
     * Calls the v2PostCapitalWithdrawApply endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  v2PostCapitalWithdrawApply (Object... optionalArgs)
    {
        return this.callAsync ("v2PostCapitalWithdrawApply", optionalArgs);
    }

    /**
     * Calls the v2PostFiatWithdraw endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  v2PostFiatWithdraw (Object... optionalArgs)
    {
        return this.callAsync ("v2PostFiatWithdraw", optionalArgs);
    }

    /**
     * Calls the v2DeleteOrder endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public CompletableFuture<Map<String, Object>>  v2DeleteOrder (Object... optionalArgs)
    {
        return this.callAsync ("v2DeleteOrder", optionalArgs);
    }

}