// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

// PublicGetApiServerTime returns a channel that yields a JSON object.
func (this *Indodax) PublicGetApiServerTime(args ...any) <-chan any {
	return this.Fetch2Async("api/server_time", "public", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(5)})
}

// PublicGetApiPairs returns a channel that yields a JSON array.
func (this *Indodax) PublicGetApiPairs(args ...any) <-chan any {
	return this.Fetch2Async("api/pairs", "public", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(5)})
}

// PublicGetApiPriceIncrements returns a channel that yields a JSON object.
func (this *Indodax) PublicGetApiPriceIncrements(args ...any) <-chan any {
	return this.Fetch2Async("api/price_increments", "public", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(5)})
}

// PublicGetApiSummaries returns a channel that yields a JSON object.
func (this *Indodax) PublicGetApiSummaries(args ...any) <-chan any {
	return this.Fetch2Async("api/summaries", "public", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(5)})
}

// PublicGetApiTickerPair returns a channel that yields a JSON object.
func (this *Indodax) PublicGetApiTickerPair(args ...any) <-chan any {
	return this.Fetch2Async("api/ticker/{pair}", "public", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(5)})
}

// PublicGetApiTickerAll returns a channel that yields a JSON object.
func (this *Indodax) PublicGetApiTickerAll(args ...any) <-chan any {
	return this.Fetch2Async("api/ticker_all", "public", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(5)})
}

// PublicGetApiTradesPair returns a channel that yields a JSON array.
func (this *Indodax) PublicGetApiTradesPair(args ...any) <-chan any {
	return this.Fetch2Async("api/trades/{pair}", "public", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(5)})
}

// PublicGetApiDepthPair returns a channel that yields a JSON object.
func (this *Indodax) PublicGetApiDepthPair(args ...any) <-chan any {
	return this.Fetch2Async("api/depth/{pair}", "public", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(5)})
}

// PublicGetTradingviewHistoryV2 returns a channel that yields a JSON array.
func (this *Indodax) PublicGetTradingviewHistoryV2(args ...any) <-chan any {
	return this.Fetch2Async("tradingview/history_v2", "public", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(5)})
}

// PrivatePostGetInfo returns a channel that yields a JSON object.
func (this *Indodax) PrivatePostGetInfo(args ...any) <-chan any {
	return this.Fetch2Async("getInfo", "private", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// PrivatePostTransHistory returns a channel that yields a JSON object.
func (this *Indodax) PrivatePostTransHistory(args ...any) <-chan any {
	return this.Fetch2Async("transHistory", "private", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// PrivatePostTrade returns a channel that yields a JSON object.
func (this *Indodax) PrivatePostTrade(args ...any) <-chan any {
	return this.Fetch2Async("trade", "private", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(1)})
}

// PrivatePostTradeHistory returns a channel that yields a JSON object.
func (this *Indodax) PrivatePostTradeHistory(args ...any) <-chan any {
	return this.Fetch2Async("tradeHistory", "private", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// PrivatePostOpenOrders returns a channel that yields a JSON object.
func (this *Indodax) PrivatePostOpenOrders(args ...any) <-chan any {
	return this.Fetch2Async("openOrders", "private", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// PrivatePostOrderHistory returns a channel that yields a JSON object.
func (this *Indodax) PrivatePostOrderHistory(args ...any) <-chan any {
	return this.Fetch2Async("orderHistory", "private", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// PrivatePostGetOrder returns a channel that yields a JSON object.
func (this *Indodax) PrivatePostGetOrder(args ...any) <-chan any {
	return this.Fetch2Async("getOrder", "private", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// PrivatePostGetOrderByClientOrderId returns a channel that yields a JSON object.
func (this *Indodax) PrivatePostGetOrderByClientOrderId(args ...any) <-chan any {
	return this.Fetch2Async("getOrderByClientOrderId", "private", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// PrivatePostCancelOrder returns a channel that yields a JSON object.
func (this *Indodax) PrivatePostCancelOrder(args ...any) <-chan any {
	return this.Fetch2Async("cancelOrder", "private", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// PrivatePostCancelByClientOrderId returns a channel that yields a JSON object.
func (this *Indodax) PrivatePostCancelByClientOrderId(args ...any) <-chan any {
	return this.Fetch2Async("cancelByClientOrderId", "private", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// PrivatePostWithdrawFee returns a channel that yields a JSON object.
func (this *Indodax) PrivatePostWithdrawFee(args ...any) <-chan any {
	return this.Fetch2Async("withdrawFee", "private", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// PrivatePostWithdrawCoin returns a channel that yields a JSON object.
func (this *Indodax) PrivatePostWithdrawCoin(args ...any) <-chan any {
	return this.Fetch2Async("withdrawCoin", "private", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// PrivatePostListDownline returns a channel that yields a JSON object.
func (this *Indodax) PrivatePostListDownline(args ...any) <-chan any {
	return this.Fetch2Async("listDownline", "private", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// PrivatePostCheckDownline returns a channel that yields a JSON object.
func (this *Indodax) PrivatePostCheckDownline(args ...any) <-chan any {
	return this.Fetch2Async("checkDownline", "private", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// PrivatePostCreateVoucher returns a channel that yields a JSON object.
func (this *Indodax) PrivatePostCreateVoucher(args ...any) <-chan any {
	return this.Fetch2Async("createVoucher", "private", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// V2GetOrder returns a channel that yields a JSON object.
func (this *Indodax) V2GetOrder(args ...any) <-chan any {
	return this.Fetch2Async("order", "v2", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// V2GetOpenOrders returns a channel that yields a JSON array.
func (this *Indodax) V2GetOpenOrders(args ...any) <-chan any {
	return this.Fetch2Async("openOrders", "v2", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// V2GetOrderHistories returns a channel that yields a JSON object.
func (this *Indodax) V2GetOrderHistories(args ...any) <-chan any {
	return this.Fetch2Async("order/histories", "v2", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// V2GetMyTrades returns a channel that yields a JSON object.
func (this *Indodax) V2GetMyTrades(args ...any) <-chan any {
	return this.Fetch2Async("myTrades", "v2", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// V2GetAccount returns a channel that yields a JSON object.
func (this *Indodax) V2GetAccount(args ...any) <-chan any {
	return this.Fetch2Async("account", "v2", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// V2GetCapitalWithdrawHistory returns a channel that yields a JSON array.
func (this *Indodax) V2GetCapitalWithdrawHistory(args ...any) <-chan any {
	return this.Fetch2Async("capital/withdraw/history", "v2", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(24)})
}

// V2GetCapitalDepositHisrec returns a channel that yields a JSON array.
func (this *Indodax) V2GetCapitalDepositHisrec(args ...any) <-chan any {
	return this.Fetch2Async("capital/deposit/hisrec", "v2", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(24)})
}

// V2GetCapitalDepositAddressList returns a channel that yields a JSON array.
func (this *Indodax) V2GetCapitalDepositAddressList(args ...any) <-chan any {
	return this.Fetch2Async("capital/deposit/address/list", "v2", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(24)})
}

// V2GetFiatOrders returns a channel that yields a JSON object.
func (this *Indodax) V2GetFiatOrders(args ...any) <-chan any {
	return this.Fetch2Async("fiat/orders", "v2", "GET", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(24)})
}

// V2PostOrder returns a channel that yields a JSON object.
func (this *Indodax) V2PostOrder(args ...any) <-chan any {
	return this.Fetch2Async("order", "v2", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}

// V2PostCapitalWithdrawApply returns a channel that yields a JSON object.
func (this *Indodax) V2PostCapitalWithdrawApply(args ...any) <-chan any {
	return this.Fetch2Async("capital/withdraw/apply", "v2", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(24)})
}

// V2PostFiatWithdraw returns a channel that yields a JSON object.
func (this *Indodax) V2PostFiatWithdraw(args ...any) <-chan any {
	return this.Fetch2Async("fiat/withdraw", "v2", "POST", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(24)})
}

// V2DeleteOrder returns a channel that yields a JSON object.
func (this *Indodax) V2DeleteOrder(args ...any) <-chan any {
	return this.Fetch2Async("order", "v2", "DELETE", GetArg(args, 0, nil), map[string]any{}, nil, map[string]any{"cost": float64(4)})
}
