from ccxt.base.types import Entry
_Dict = dict[str, object]
_List = list[object]


class ImplicitAPI:
    public_get_api_server_time = publicGetApiServerTime = Entry[_Dict]('api/server_time', 'public', 'GET', {'cost': 5})
    public_get_api_pairs = publicGetApiPairs = Entry[_List]('api/pairs', 'public', 'GET', {'cost': 5})
    public_get_api_price_increments = publicGetApiPriceIncrements = Entry[_Dict]('api/price_increments', 'public', 'GET', {'cost': 5})
    public_get_api_summaries = publicGetApiSummaries = Entry[_Dict]('api/summaries', 'public', 'GET', {'cost': 5})
    public_get_api_ticker_pair = publicGetApiTickerPair = Entry[_Dict]('api/ticker/{pair}', 'public', 'GET', {'cost': 5})
    public_get_api_ticker_all = publicGetApiTickerAll = Entry[_Dict]('api/ticker_all', 'public', 'GET', {'cost': 5})
    public_get_api_trades_pair = publicGetApiTradesPair = Entry[_List]('api/trades/{pair}', 'public', 'GET', {'cost': 5})
    public_get_api_depth_pair = publicGetApiDepthPair = Entry[_Dict]('api/depth/{pair}', 'public', 'GET', {'cost': 5})
    public_get_tradingview_history_v2 = publicGetTradingviewHistoryV2 = Entry[_List]('tradingview/history_v2', 'public', 'GET', {'cost': 5})
    private_post_getinfo = privatePostGetInfo = Entry[_Dict]('getInfo', 'private', 'POST', {'cost': 4})
    private_post_transhistory = privatePostTransHistory = Entry[_Dict]('transHistory', 'private', 'POST', {'cost': 4})
    private_post_trade = privatePostTrade = Entry[_Dict]('trade', 'private', 'POST', {'cost': 1})
    private_post_tradehistory = privatePostTradeHistory = Entry[_Dict]('tradeHistory', 'private', 'POST', {'cost': 4})
    private_post_openorders = privatePostOpenOrders = Entry[_Dict]('openOrders', 'private', 'POST', {'cost': 4})
    private_post_orderhistory = privatePostOrderHistory = Entry[_Dict]('orderHistory', 'private', 'POST', {'cost': 4})
    private_post_getorder = privatePostGetOrder = Entry[_Dict]('getOrder', 'private', 'POST', {'cost': 4})
    private_post_getorderbyclientorderid = privatePostGetOrderByClientOrderId = Entry[_Dict]('getOrderByClientOrderId', 'private', 'POST', {'cost': 4})
    private_post_cancelorder = privatePostCancelOrder = Entry[_Dict]('cancelOrder', 'private', 'POST', {'cost': 4})
    private_post_cancelbyclientorderid = privatePostCancelByClientOrderId = Entry[_Dict]('cancelByClientOrderId', 'private', 'POST', {'cost': 4})
    private_post_withdrawfee = privatePostWithdrawFee = Entry[_Dict]('withdrawFee', 'private', 'POST', {'cost': 4})
    private_post_withdrawcoin = privatePostWithdrawCoin = Entry[_Dict]('withdrawCoin', 'private', 'POST', {'cost': 4})
    private_post_listdownline = privatePostListDownline = Entry[_Dict]('listDownline', 'private', 'POST', {'cost': 4})
    private_post_checkdownline = privatePostCheckDownline = Entry[_Dict]('checkDownline', 'private', 'POST', {'cost': 4})
    private_post_createvoucher = privatePostCreateVoucher = Entry[_Dict]('createVoucher', 'private', 'POST', {'cost': 4})
    deadman_post_countdowncancelall = deadmanPostCountdownCancelAll = Entry[_Dict]('countdownCancelAll', 'deadman', 'POST', {'cost': 20})
    v2_get_order = v2GetOrder = Entry[_Dict]('order', 'v2', 'GET', {'cost': 4})
    v2_get_openorders = v2GetOpenOrders = Entry[_List]('openOrders', 'v2', 'GET', {'cost': 4})
    v2_get_order_histories = v2GetOrderHistories = Entry[_Dict]('order/histories', 'v2', 'GET', {'cost': 4})
    v2_get_mytrades = v2GetMyTrades = Entry[_Dict]('myTrades', 'v2', 'GET', {'cost': 4})
    v2_get_account = v2GetAccount = Entry[_Dict]('account', 'v2', 'GET', {'cost': 4})
    v2_get_capital_withdraw_history = v2GetCapitalWithdrawHistory = Entry[_List]('capital/withdraw/history', 'v2', 'GET', {'cost': 24})
    v2_get_capital_deposit_hisrec = v2GetCapitalDepositHisrec = Entry[_List]('capital/deposit/hisrec', 'v2', 'GET', {'cost': 24})
    v2_get_capital_deposit_address_list = v2GetCapitalDepositAddressList = Entry[_List]('capital/deposit/address/list', 'v2', 'GET', {'cost': 24})
    v2_get_fiat_orders = v2GetFiatOrders = Entry[_Dict]('fiat/orders', 'v2', 'GET', {'cost': 24})
    v2_post_order = v2PostOrder = Entry[_Dict]('order', 'v2', 'POST', {'cost': 4})
    v2_post_capital_withdraw_apply = v2PostCapitalWithdrawApply = Entry[_Dict]('capital/withdraw/apply', 'v2', 'POST', {'cost': 24})
    v2_post_fiat_withdraw = v2PostFiatWithdraw = Entry[_Dict]('fiat/withdraw', 'v2', 'POST', {'cost': 24})
    v2_delete_order = v2DeleteOrder = Entry[_Dict]('order', 'v2', 'DELETE', {'cost': 4})
