<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class indodax extends \ccxt\Exchange {
    /**
     * @return array<string, mixed>
     */
    public function public_get_api_server_time($params = array()) {
        return $this->request('api/server_time', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return list<mixed>
     */
    public function public_get_api_pairs($params = array()) {
        return $this->request('api/pairs', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return array<string, mixed>
     */
    public function public_get_api_price_increments($params = array()) {
        return $this->request('api/price_increments', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return array<string, mixed>
     */
    public function public_get_api_summaries($params = array()) {
        return $this->request('api/summaries', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return array<string, mixed>
     */
    public function public_get_api_ticker_pair($params = array()) {
        return $this->request('api/ticker/{pair}', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return array<string, mixed>
     */
    public function public_get_api_ticker_all($params = array()) {
        return $this->request('api/ticker_all', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return list<mixed>
     */
    public function public_get_api_trades_pair($params = array()) {
        return $this->request('api/trades/{pair}', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return array<string, mixed>
     */
    public function public_get_api_depth_pair($params = array()) {
        return $this->request('api/depth/{pair}', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return list<mixed>
     */
    public function public_get_tradingview_history_v2($params = array()) {
        return $this->request('tradingview/history_v2', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return array<string, mixed>
     */
    public function private_post_getinfo($params = array()) {
        return $this->request('getInfo', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function private_post_transhistory($params = array()) {
        return $this->request('transHistory', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function private_post_trade($params = array()) {
        return $this->request('trade', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    /**
     * @return array<string, mixed>
     */
    public function private_post_tradehistory($params = array()) {
        return $this->request('tradeHistory', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function private_post_openorders($params = array()) {
        return $this->request('openOrders', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function private_post_orderhistory($params = array()) {
        return $this->request('orderHistory', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function private_post_getorder($params = array()) {
        return $this->request('getOrder', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function private_post_getorderbyclientorderid($params = array()) {
        return $this->request('getOrderByClientOrderId', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function private_post_cancelorder($params = array()) {
        return $this->request('cancelOrder', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function private_post_cancelbyclientorderid($params = array()) {
        return $this->request('cancelByClientOrderId', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function private_post_withdrawfee($params = array()) {
        return $this->request('withdrawFee', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function private_post_withdrawcoin($params = array()) {
        return $this->request('withdrawCoin', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function private_post_listdownline($params = array()) {
        return $this->request('listDownline', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function private_post_checkdownline($params = array()) {
        return $this->request('checkDownline', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function private_post_createvoucher($params = array()) {
        return $this->request('createVoucher', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function deadman_post_countdowncancelall($params = array()) {
        return $this->request('countdownCancelAll', 'deadman', 'POST', $params, null, null, array("cost" => 20));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2_get_order($params = array()) {
        return $this->request('order', 'v2', 'GET', $params, null, null, array("cost" => 4));
    }
    /**
     * @return list<mixed>
     */
    public function v2_get_openorders($params = array()) {
        return $this->request('openOrders', 'v2', 'GET', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2_get_order_histories($params = array()) {
        return $this->request('order/histories', 'v2', 'GET', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2_get_mytrades($params = array()) {
        return $this->request('myTrades', 'v2', 'GET', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2_get_account($params = array()) {
        return $this->request('account', 'v2', 'GET', $params, null, null, array("cost" => 4));
    }
    /**
     * @return list<mixed>
     */
    public function v2_get_capital_withdraw_history($params = array()) {
        return $this->request('capital/withdraw/history', 'v2', 'GET', $params, null, null, array("cost" => 24));
    }
    /**
     * @return list<mixed>
     */
    public function v2_get_capital_deposit_hisrec($params = array()) {
        return $this->request('capital/deposit/hisrec', 'v2', 'GET', $params, null, null, array("cost" => 24));
    }
    /**
     * @return list<mixed>
     */
    public function v2_get_capital_deposit_address_list($params = array()) {
        return $this->request('capital/deposit/address/list', 'v2', 'GET', $params, null, null, array("cost" => 24));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2_get_fiat_orders($params = array()) {
        return $this->request('fiat/orders', 'v2', 'GET', $params, null, null, array("cost" => 24));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2_post_order($params = array()) {
        return $this->request('order', 'v2', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2_post_capital_withdraw_apply($params = array()) {
        return $this->request('capital/withdraw/apply', 'v2', 'POST', $params, null, null, array("cost" => 24));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2_post_fiat_withdraw($params = array()) {
        return $this->request('fiat/withdraw', 'v2', 'POST', $params, null, null, array("cost" => 24));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2_delete_order($params = array()) {
        return $this->request('order', 'v2', 'DELETE', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function publicGetApiServerTime($params = array()) {
        return $this->request('api/server_time', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return list<mixed>
     */
    public function publicGetApiPairs($params = array()) {
        return $this->request('api/pairs', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return array<string, mixed>
     */
    public function publicGetApiPriceIncrements($params = array()) {
        return $this->request('api/price_increments', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return array<string, mixed>
     */
    public function publicGetApiSummaries($params = array()) {
        return $this->request('api/summaries', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return array<string, mixed>
     */
    public function publicGetApiTickerPair($params = array()) {
        return $this->request('api/ticker/{pair}', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return array<string, mixed>
     */
    public function publicGetApiTickerAll($params = array()) {
        return $this->request('api/ticker_all', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return list<mixed>
     */
    public function publicGetApiTradesPair($params = array()) {
        return $this->request('api/trades/{pair}', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return array<string, mixed>
     */
    public function publicGetApiDepthPair($params = array()) {
        return $this->request('api/depth/{pair}', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return list<mixed>
     */
    public function publicGetTradingviewHistoryV2($params = array()) {
        return $this->request('tradingview/history_v2', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    /**
     * @return array<string, mixed>
     */
    public function privatePostGetInfo($params = array()) {
        return $this->request('getInfo', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function privatePostTransHistory($params = array()) {
        return $this->request('transHistory', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function privatePostTrade($params = array()) {
        return $this->request('trade', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    /**
     * @return array<string, mixed>
     */
    public function privatePostTradeHistory($params = array()) {
        return $this->request('tradeHistory', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function privatePostOpenOrders($params = array()) {
        return $this->request('openOrders', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function privatePostOrderHistory($params = array()) {
        return $this->request('orderHistory', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function privatePostGetOrder($params = array()) {
        return $this->request('getOrder', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function privatePostGetOrderByClientOrderId($params = array()) {
        return $this->request('getOrderByClientOrderId', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function privatePostCancelOrder($params = array()) {
        return $this->request('cancelOrder', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function privatePostCancelByClientOrderId($params = array()) {
        return $this->request('cancelByClientOrderId', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function privatePostWithdrawFee($params = array()) {
        return $this->request('withdrawFee', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function privatePostWithdrawCoin($params = array()) {
        return $this->request('withdrawCoin', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function privatePostListDownline($params = array()) {
        return $this->request('listDownline', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function privatePostCheckDownline($params = array()) {
        return $this->request('checkDownline', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function privatePostCreateVoucher($params = array()) {
        return $this->request('createVoucher', 'private', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function deadmanPostCountdownCancelAll($params = array()) {
        return $this->request('countdownCancelAll', 'deadman', 'POST', $params, null, null, array("cost" => 20));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2GetOrder($params = array()) {
        return $this->request('order', 'v2', 'GET', $params, null, null, array("cost" => 4));
    }
    /**
     * @return list<mixed>
     */
    public function v2GetOpenOrders($params = array()) {
        return $this->request('openOrders', 'v2', 'GET', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2GetOrderHistories($params = array()) {
        return $this->request('order/histories', 'v2', 'GET', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2GetMyTrades($params = array()) {
        return $this->request('myTrades', 'v2', 'GET', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2GetAccount($params = array()) {
        return $this->request('account', 'v2', 'GET', $params, null, null, array("cost" => 4));
    }
    /**
     * @return list<mixed>
     */
    public function v2GetCapitalWithdrawHistory($params = array()) {
        return $this->request('capital/withdraw/history', 'v2', 'GET', $params, null, null, array("cost" => 24));
    }
    /**
     * @return list<mixed>
     */
    public function v2GetCapitalDepositHisrec($params = array()) {
        return $this->request('capital/deposit/hisrec', 'v2', 'GET', $params, null, null, array("cost" => 24));
    }
    /**
     * @return list<mixed>
     */
    public function v2GetCapitalDepositAddressList($params = array()) {
        return $this->request('capital/deposit/address/list', 'v2', 'GET', $params, null, null, array("cost" => 24));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2GetFiatOrders($params = array()) {
        return $this->request('fiat/orders', 'v2', 'GET', $params, null, null, array("cost" => 24));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2PostOrder($params = array()) {
        return $this->request('order', 'v2', 'POST', $params, null, null, array("cost" => 4));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2PostCapitalWithdrawApply($params = array()) {
        return $this->request('capital/withdraw/apply', 'v2', 'POST', $params, null, null, array("cost" => 24));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2PostFiatWithdraw($params = array()) {
        return $this->request('fiat/withdraw', 'v2', 'POST', $params, null, null, array("cost" => 24));
    }
    /**
     * @return array<string, mixed>
     */
    public function v2DeleteOrder($params = array()) {
        return $this->request('order', 'v2', 'DELETE', $params, null, null, array("cost" => 4));
    }
}
